
export const SET_PAGE_NAME = "SET_PAGE_NAME"

export const GET_PROJECTS = "GET_PROJECTS"

export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT"

export const OPEN_DETAILS = "OPEN_DETAILS"


export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST'

export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'

export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'